name: Deploy TransfermarktScraper to Azure (via Azure Login)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu:25.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.5

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Publish Web Project
        run: dotnet publish TransfermarktScraper.Web/TransfermarktScraper.Web.csproj --configuration Release --output ./publish/web

      - name: Publish API Project
        run: dotnet publish TransfermarktScraper.ApiService/TransfermarktScraper.ApiService.csproj --configuration Release --output ./publish/api

      - name: Merge output into one folder
        run: |
          mkdir ./finalpublish
          cp -r ./publish/web/* ./finalpublish/
          cp -r ./publish/api/* ./finalpublish/

      - name: Zip deployment package
        run: zip -r deploy-package.zip ./finalpublish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ASP-ScraperDevops-b9e4'
          package: deploy-package.zip
